[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.25"
optimizer = true
optimizer_runs = 200
via_ir = true
fs_permissions = [{ access = "read", path = "../../node_modules" }]

remappings = [
    "@openzeppelin/contracts/=lib/v4-core/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/=lib/v4-core/lib/openzeppelin-contracts/",
    "@openzeppelin-contracts-5.2.0-rc.1/=lib/v4-core/lib/openzeppelin-contracts/contracts/",
    "@openzeppelin-contracts/=lib/v4-core/lib/openzeppelin-contracts/contracts/",
    "@uniswap/v4-core/=lib/v4-core/",
    "@uniswap/v4-periphery/=lib/v4-periphery/",
    "@flarenetwork/flare-periphery-contracts/coston2/=lib/flare-foundry-periphery-package/src/coston2/",
    "@chainlink/=node_modules/@chainlink/",
    "@layerzerolabs/lz-evm-oapp-v2/contracts/=lib/layerzero-v2/packages/layerzero-v2/evm/oapp/contracts/",
    "@layerzerolabs/lz-evm-protocol-v2/contracts/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol/contracts/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/v4-core/lib/solmate/src/"
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC}"
baseSepolia = "${BASE_SEPOLIA_RPC}"
coston2 = "${COSTON2_RPC}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
baseSepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
